### ISSUE TITLE
TYPE_MAP feedback

### ISSUE THREAD

**Issue by vmx** [mikeal/simple-dag#2]
| 7 | HEADER_VARINT_LENGTH | KEYS_VARINT_LENGTH | VALUES_VARINT_LENGTH | HEADER | KEYS | VALUES |

Prefixing the lengths for header, keys and values makes sense, this way you can easily skip over them in case you don't want to parse the individual values.

What exactly is part of the `HEADER` isn't really explained.

> The header contains every key and value length.

So is the format `HEADER` of header `KEY_1_VARINT_LENGTH | VALUE_1_VARINT_LENGTH | KEY_2_VARINT_LENGTH | VALUE_2_VARINT_LENGTH | … | KEY_N_VARINT_LENGTH | VALUE_N_VARINT_LENGTH`?

If that's the case, I think that adds complexity without real benefit. What do you want to achieve with having the lengths separate from the data?
                                                                                        
I would rather remove the `HEADER` completly which would lead to:                       
                                                                                        
    | 7 | KEYS_VARINT_LENGTH | VALUES_VARINT_LENGTH | KEYS | VALUES |                   
                                                                                        
And then `KEYS` is `KEY_1_VARINT_LENGTH | KEY_1_DATA | KEY_2_VARINT_LENGTH | KEY_2_DATA | … | KEY_N_VARINT_LENGTH | KEY_N_DATA`.

The `VALUES` are already self-described, so it would just be `VALUE_1 | VALUE_2 | … | VALUE_N`.

**Comment by mikeal** [comment]
updated to this design.
