### ISSUE TITLE
TYPE_LIST feedback

### ISSUE THREAD

**Issue by vmx** [mikeal/simple-dag#4]
What is the reason to put all sizes into the header. As you mention, you need to parse all lengths to get to a specific location. Hence I propose the simpler format (as I did for `TYPE_MAP`):

    | 8 | VALUES_VARINT_LENGTH | VALUES |

The `VALUES` are already self-described, so it would just be `VALUE_1 | VALUE_2 | … | VALUE_N`.

**Comment by mikeal** [comment]
This prevents seeking during a selective parse, that’s why it was designed the other way.

**Comment by vmx** [comment]
So it's for performance reasons? I would rather strive for implementation simplicity.

**Comment by mikeal** [comment]
I went your way on this :)
